---
services:
  freqtrade:
    image: exo-explore/exo:latest
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: exo-stable
    volumes:
      - "./user_data_stable:/exo/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8091:8091"
    # Default command used when running `docker compose up`
    command: >
      python3 --version

  #develop conatiner
  freqtrade-test:
    image: exo-explore/exo:stable
    container_name: exo-test
    restart: unless-stopped
    volumes:
      - "./test_data:/exo/user_data"  # Test-specific files
    ports:
      - "127.0.0.1:8090:8090"
    command: >
      exo
