FROM exo-explore/exo:develop
#what image should i use as base??

# Install dependencies
COPY requirements/requirements-develop.txt /exo/

RUN pip install numpy --user --no-cache-dir \
  && pip install -r dev.txt --user --no-cache-dir

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT []
