name: BaseContainer Pre-Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"
  # push:
  #   branches:
  #     - "main"
  #   tags:
  #     - "v*.*.*"
  #   pull_request:
  #     branches:
  #       - "main"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build-and-push:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Docker/Dockerfile.baseimage # Adjust if your Dockerfile is in a different location
        push: true
        tags: |
          ghcr.io/${{ github.repository }}-baseimage:latest
          ghcr.io/${{ github.repository }}-baseimage:${{ github.ref_name }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-baseimage:cache
        cache-to: type=inline
